version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ContactManagement;User=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - db
    networks:
      - contact-management-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - contact-management-network

networks:
  contact-management-network:
    driver: bridge

volumes:
  sqlserver-data:
